# Generated by Django 6.0.6 on 2026-06-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='room_images/')),
            ],
        ),
    ]
